Basic attempt at releasing. Uses OSSRH from Sonatype to release.
martinvisser/kover-maven-plugin pull request #44
Opened 2023-08-25 15:17 UTC by lugaramirez

Based on both https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven and https://central.sonatype.org/publish/publish-maven/#review-requirements.

What's missing to make a proper release pipeline is adding the secrets as stated here: https://docs.github.com/en/actions/security-guides/encrypted-secrets

2023-08-25 15:38 UTC, lugaramirez commented
Updated the PR by adding the secret as stated on the guidelines, but, the secrets where created on the forked repo; I don't know if github will pull them from there

2023-08-30 18:27 UTC, martinvisser requested changes

2023-08-30 18:27 UTC, martinvisser commented on pom.xml
> +        <url>https://github.com/martinvisser/kover-maven-plugin/tree/master</url>
```suggestion
        <url>https://github.com/martinvisser/kover-maven-plugin</url>
```

2023-08-30 18:27 UTC, martinvisser commented on pom.xml
> +            <plugin>
Let's move these to some `release` profile.

2023-08-31 17:36 UTC, merged